" ### Basics ###
set nocompatible
set directory=$HOME/.vim/swp
set nobackup nowritebackup noswapfile autoread
set mouse=a
let mapleader=","
set clipboard=unnamed,unnamedplus "use the system clipboard
set backspace=2
set undodir=~/.vim/undo
set undofile
set undolevels=1000
set undoreload=10000

" ### Detect OSX ###
let s:on_osx=0
if has("unix")
    let s:uname=system("uname")
    if s:uname=="Darwin\n"
        let s:on_osx=1
    endif
endif

" ### Vundle ###
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'benmills/vimux'
Plugin 'molokai'
Plugin 'kien/ctrlp.vim'
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'tpope/vim-surround'
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'guns/xterm-color-table.vim'
Plugin 'godlygeek/tabular'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/syntastic'
Plugin 'christoomey/vim-tmux-navigator'
" YouCompleteMe currently fails to build on my linux machine
if s:on_osx
    Plugin 'Valloric/YouCompleteMe'
    Plugin 'marijnh/tern_for_vim'
endif
call vundle#end()
filetype plugin indent on

" ### Colours ###
syntax on
silent! colorscheme molokai
let g:molokai_original=1
let g:rehash256=1
set background=dark
set t_Co=256

" ### Lines ###
set number
set wrap
" colorcolumn introduced in vim 7.3
if exists("&colorcolumn")
    let &colorcolumn=join(range(121,500),",")
    highlight ColorColumn ctermbg=234
endif

" ### Tabs -> Spaces ###
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
autocmd FileType yaml setlocal shiftwidth=2 tabstop=2

" ### Search ###
set incsearch
set hlsearch
set ignorecase
set smartcase

" ### netrw ###
let g:netrw_liststyle=3

" ### Javascript ###
" Turn JSX highlighting on for all files
let g:jsx_ext_required = 0

" ### indent-guides (:help indent-guides) ###
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_default_mapping = 0
let g:indent_guides_auto_colors = 0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=234
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=235

" ### Leader Aliases ###
nnoremap <Leader>p :CtrlP<CR>
nnoremap <Leader>tr :VimuxRunCommand(expand('%:p'))<CR>
nnoremap <Leader>trl :VimuxRunLastCommand<CR>
nnoremap <Leader>trp :VimuxPromptCommand<CR>
nnoremap <Leader>f :Explore!<CR>

" ### Status Line / Airline ###
set laststatus=2
let g:airline_powerline_fonts = 1

" ### Syntastic ###
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0 "Use :lopen and :lclose to show the list of errors
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
" Perl
let g:syntastic_enable_perl_checker = 0 "Disabled by default - will run BEGIN blocks
let g:syntastic_perl_checkers = ['perl']

" ### YouCompleteMe/Autocomplete ###
set completeopt=longest,menuone
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

" ### Setup for seemless tmux integration
let g:tmux_navigator_no_mappings = 1
nnoremap <silent> <C-w>h :TmuxNavigateLeft<cr>
nnoremap <silent> <C-w>j :TmuxNavigateDown<cr>
nnoremap <silent> <C-w>k :TmuxNavigateUp<cr>
nnoremap <silent> <C-w>l :TmuxNavigateRight<cr>

" ### ctrlp ###
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git'

" ### Include .vimrc.local file for local overrides
if filereadable(glob("~/.vimrc.local")) 
    source ~/.vimrc.local
endif
