source ~/.zprezto/init.zsh

export PATH="/usr/local/bin:$PATH"
export VISUAL=vim
export EDITOR=$VISUAL
export GIT_AUTHOR_NAME="Matthew Benton"
export GIT_AUTHOR_EMAIL="me@mattbenton.co.uk"
export GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME
export GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL

# aliases
alias mountprivate='hdiutil attach ~/Dropbox/private.dmg -stdinpass'
alias glog='git log --oneline --decorate --graph --all'
