source ~/.zprezto/init.zsh
export VISUAL=vim
export EDITOR=$VISUAL

# aliases
alias glog='git log --oneline --decorate --graph --all'

# perlbrew
if [ -e ~/perl5/perlbrew/etc/bashrc ]; then
    source ~/perl5/perlbrew/etc/bashrc
fi

if [[ `uname` == 'Darwin' ]]; then
    if [ -e ~/.zshrc.osx ]; then
        source ~/.zshrc.osx
    fi
fi

# source local extras if it exists
if [ -e ~/.zshrc.local ]; then
    source ~/.zshrc.local
fi

# Function to tar.gz up a directory
targzdir() {
  tar --exclude-vcs --exclude-vcs-ignores -cvzf $1.tar.gz $1
}
