[colors.bright]
black = "#686f9a"
blue = "#00a3cc"
cyan = "#7a5ccc"
green = "#5ccc96"
magenta = "#f2ce00"
red = "#e33400"
white = "#f0f1ce"
yellow = "#b3a1e6"

[colors.normal]
black = "#000000"
blue = "#00a3cc"
cyan = "#7a5ccc"
green = "#5ccc96"
magenta = "#f2ce00"
red = "#e33400"
white = "#686f9a"
yellow = "#b3a1e6"

[colors.primary]
background = "#0f111b"
foreground = "#ecf0c1"

[env]
TERM = "xterm-256color-italic"

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 2

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Command"

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[window]
decorations = "Buttonless"

[window.padding]
x = 5
y = 0
